architecture: DenseNet201
pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 12
activation: sigmoid
weights: imagenet
shape: [256, 256, 3]
optimizer: Adam
batch: 16
lr: 0.0005
copyWeights: true
metrics:
  - accuracy
  - macro_f1
primary_metric: val_loss
primary_metric_mode: auto
callbacks:
  EarlyStopping:
    patience: 5
    monitor: val_loss
    mode: auto
    verbose: 1
  ReduceLROnPlateau:
    patience: 3
    factor: 0.3
    monitor: val_loss
    mode: auto
    cooldown: 1
    verbose: 1
loss: categorical_crossentropy
stages:
  - epochs: 50
