architecture: DenseNet201
pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 28
activation: sigmoid
weights: imagenet
shape: [224, 224, 4]
optimizer: Adam
batch: 16
lr: 0.005
copyWeights: true
metrics:
  - binary_accuracy
  - macro_f1
primary_metric: val_binary_accuracy
primary_metric_mode: max
callbacks:
  EarlyStopping:
    patience: 3
    monitor: val_macro_f1
    mode: max
    verbose: 1
  ReduceLROnPlateau:
    patience: 2
    factor: 0.3
    monitor: val_binary_accuracy
    mode: max
    cooldown: 1
    verbose: 1
loss: binary_crossentropy
stages:
  - epochs: 10
