architecture: inceptionv3
pooling: avg
augmentation:
 Fliplr: 0.5
 Flipud: 0.5
classes: 28
activation: sigmoid
weights: imagenet
shape: [256, 256, 4]
optimizer: Adam
batch: 32
copyWeights: true
metrics:
  - binary_accuracy
  - macro_f1
primary_metric: val_loss
primary_metric_mode: auto
callbacks:
  EarlyStopping:
    patience: 3
    monitor: val_loss
    mode: auto
    verbose: 1
  ReduceLROnPlateau:
    patience: 2
    factor: 0.3
    monitor: val_loss
    mode: auto
    cooldown: 1
    verbose: 1
loss: binary_crossentropy
stages:
  - epochs: 10
