backbone: mobilenetv2
architecture: DeepLabV3
augmentation:
 Fliplr: 0.5

classes: 1
activation: sigmoid
encoder_weights: pascal_voc
shape: [384, 384, 3]
optimizer: Adam
batch: 2
folds: 1
metrics:
  - binary_accuracy
primary_metric: val_loss
callbacks:
  EarlyStopping:
    patience: 3
    monitor: val_loss
    verbose: 1
  ReduceLROnPlateau:
    patience: 2
    factor: 0.5
    monitor: val_loss
    mode: auto
    cooldown: 5
    verbose: 1
loss: binary_crossentropy
stages:
  - epochs: 1
    negatives: 1
