backbone: resnet34
architecture: Unet
augmentation:
 Fliplr: 0.5

classes: 1
activation: sigmoid
encoder_weights: imagenet
shape: [101, 101, 3]
optimizer: Adam
batch: 2
metrics:
  - binary_accuracy
primary_metric: val_loss
callbacks:
  EarlyStopping:
    patience: 5
    monitor: val_loss
    verbose: 1
  ReduceLROnPlateau:
    patience: 4
    factor: 0.5
    monitor: val_loss
    mode: auto
    cooldown: 5
    verbose: 1
loss: binary_crossentropy
stages:
  - epochs: 10
    negatives: real
